"""Tests for zero_keras layers."""

import inspect
from unittest.mock import MagicMock
from zero_keras import layers


def test_layers():
    layer_names = [
        "Activation",
        "ActivityRegularization",
        "Add",
        "AdditiveAttention",
        "AlphaDropout",
        "Attention",
        "AugMix",
        "AutoContrast",
        "Average",
        "AveragePooling1D",
        "AveragePooling2D",
        "AveragePooling3D",
        "AvgPool1D",
        "AvgPool2D",
        "AvgPool3D",
        "BatchNormalization",
        "Bidirectional",
        "CategoryEncoding",
        "CenterCrop",
        "Concatenate",
        "Conv1D",
        "Conv1DTranspose",
        "Conv2D",
        "Conv2DTranspose",
        "Conv3D",
        "Conv3DTranspose",
        "ConvLSTM1D",
        "ConvLSTM2D",
        "ConvLSTM3D",
        "Convolution1D",
        "Convolution1DTranspose",
        "Convolution2D",
        "Convolution2DTranspose",
        "Convolution3D",
        "Convolution3DTranspose",
        "Cropping1D",
        "Cropping2D",
        "Cropping3D",
        "CutMix",
        "Dense",
        "DepthwiseConv1D",
        "DepthwiseConv2D",
        "Discretization",
        "Dot",
        "Dropout",
        "ELU",
        "EinsumDense",
        "Embedding",
        "Equalization",
        "Flatten",
        "FlaxLayer",
        "GRU",
        "GRUCell",
        "GaussianDropout",
        "GaussianNoise",
        "GlobalAveragePooling1D",
        "GlobalAveragePooling2D",
        "GlobalAveragePooling3D",
        "GlobalAvgPool1D",
        "GlobalAvgPool2D",
        "GlobalAvgPool3D",
        "GlobalMaxPool1D",
        "GlobalMaxPool2D",
        "GlobalMaxPool3D",
        "GlobalMaxPooling1D",
        "GlobalMaxPooling2D",
        "GlobalMaxPooling3D",
        "GroupNormalization",
        "GroupQueryAttention",
        "HashedCrossing",
        "Hashing",
        "Identity",
        "InputLayer",
        "InputSpec",
        "IntegerLookup",
        "JaxLayer",
        "LSTM",
        "LSTMCell",
        "Lambda",
        "LayerNormalization",
        "LeakyReLU",
        "Masking",
        "MaxNumBoundingBoxes",
        "MaxPool1D",
        "MaxPool2D",
        "MaxPool3D",
        "MaxPooling1D",
        "MaxPooling2D",
        "MaxPooling3D",
        "Maximum",
        "MelSpectrogram",
        "Minimum",
        "MixUp",
        "MultiHeadAttention",
        "Multiply",
        "Normalization",
        "PReLU",
        "Permute",
        "Pipeline",
        "RMSNormalization",
        "RNN",
        "RandAugment",
        "RandomBrightness",
        "RandomColorDegeneration",
        "RandomColorJitter",
        "RandomContrast",
        "RandomCrop",
        "RandomElasticTransform",
        "RandomErasing",
        "RandomFlip",
        "RandomGaussianBlur",
        "RandomGrayscale",
        "RandomHue",
        "RandomInvert",
        "RandomPerspective",
        "RandomPosterization",
        "RandomRotation",
        "RandomSaturation",
        "RandomSharpness",
        "RandomShear",
        "RandomTranslation",
        "RandomZoom",
        "ReLU",
        "RepeatVector",
        "Rescaling",
        "Reshape",
        "Resizing",
        "STFTSpectrogram",
        "SeparableConv1D",
        "SeparableConv2D",
        "SeparableConvolution1D",
        "SeparableConvolution2D",
        "SimpleRNN",
        "SimpleRNNCell",
        "Softmax",
        "Solarization",
        "SpatialDropout1D",
        "SpatialDropout2D",
        "SpatialDropout3D",
        "SpectralNormalization",
        "StackedRNNCells",
        "StringLookup",
        "Subtract",
        "TFSMLayer",
        "TextVectorization",
        "TimeDistributed",
        "TorchModuleWrapper",
        "UnitNormalization",
        "UpSampling1D",
        "UpSampling2D",
        "UpSampling3D",
        "Wrapper",
        "ZeroPadding1D",
        "ZeroPadding2D",
        "ZeroPadding3D",
    ]
    for name in layer_names:
        layer_cls = getattr(layers, name)
        sig = inspect.signature(layer_cls.__init__)
        kwargs = {}
        for param_name, param in sig.parameters.items():
            if param_name in ("self", "kwargs", "args"):
                continue
            if param.default is inspect.Parameter.empty:
                kwargs[param_name] = MagicMock()
        layer_cls(**kwargs)


def test_layer_call():
    import numpy as np

    x = np.random.rand(2, 2).astype(np.float32)
    layer = layers.Layer()
    layer(x)
